language: node_js
node_js:
- 7
branches:
  only:
  - master
  - /^greenkeeper/.*$/
install:
- npm install
script:
- npm run travis-test
- npm run build
addons:
  code_climate:
    repo_token: "$CODE_CLIMATE"
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: "$HEROKU_KEY"
  app: "$HEROKU_APP"
before_install:
- openssl aes-256-cbc -K $encrypted_68faba75cfa8_key -iv $encrypted_68faba75cfa8_iv
  -in service_account.json.enc -out service_account.json -d
